import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light scroll-smooth" dir="ltr">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="A description of my Next.js 14 app" />
        <link
          rel="stylesheet"
          href="/assets/libs/tiny-slider/tiny-slider.css"
        />
        <link
          rel="stylesheet"
          href="/assets/libs/@iconscout/unicons/css/line.css"
        />
        <link
          rel="stylesheet"
          href="/assets/libs/@mdi/font/css/materialdesignicons.min.css"
        />
        <link rel="stylesheet" href="/assets/css/tailwind.css" />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
